[workspace]

resolver = "2"

members = [
    "ext/hip_runtime-sys",
    "ext/amd_comgr-sys",
    "comgr",
    "cuda_base",
    "cuda_types",
    "detours-sys",
    "level_zero-sys",
    "level_zero",
    "spirv_tools-sys",
    "zluda",
    "zluda_dump",
    "zluda_lib",
    "zluda_inject",
    "zluda_redirect",
    "zluda_ml",
    "ptx",
    "ptx_parser",
    "ptx_parser_macros",
    "ptx_parser_macros_impl",
]

default-members = ["zluda_lib", "zluda_ml", "zluda_inject", "zluda_redirect"]

[patch.crates-io]
rspirv = { git = 'https://github.com/vosen/rspirv', rev = '9826e59a232c4a426482cda12f88d11bfda3ff9c' }
spirv_headers = { git = 'https://github.com/vosen/rspirv', rev = '9826e59a232c4a426482cda12f88d11bfda3ff9c' }
