[package]
name = "zluda_sparse"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
name = "cusparse"

[dependencies]
cuda_base = { path = "../cuda_base" }
cuda_types = { path = "../cuda_types" }

[package.metadata.zluda]
linux_symlinks = [
    "libcusparse.so.12",
]
