[package]
name = "ptx"
version = "0.0.0"
authors = ["Andrzej Janik <vosen@vosen.pl>"]
edition = "2021"

[lib]

[dependencies]
ptx_parser = { path = "../ptx_parser" }
rspirv = "0.7"
spirv_headers = "1.5" 
quick-error = "1.2"
thiserror = "1.0"
bit-vec = "0.6"
half ="1.6"
bitflags = "1.2"

[dev-dependencies]
hip_runtime-sys = { path = "../hip_runtime-sys" }
tempfile = "3"
spirv_tools-sys = { path = "../spirv_tools-sys" }
paste = "1.0"
cuda-driver-sys = "0.3.0"
