[package]
name = "zluda_dump_blas"
version = "0.0.0"
authors = ["Andrzej Janik <vosen@vosen.pl>"]
edition = "2021"

[lib]
name = "zluda_dump_blas"
crate-type = ["cdylib"]

[dependencies]

[package.metadata.zluda]
linux_symlinks = [
    "dump/libcublas.so",
    "dump/libcublas.so.12"
]
