[package]
name = "ptx_parser"
version = "0.1.0"
edition = "2021"

[dependencies]
logos = "0.14"
winnow = { version =  "0.6.18" }
gen = { path = "../gen" }
thiserror = "1.0"
bitflags = "1.2"
rustc-hash = "2.0.0"
