version: 2
build:
  os: ubuntu-lts-latest
  tools:
    rust: latest
  jobs:
    install:
      - cargo install mdbook --root .
    build:
      html:
        - ./bin/mdbook build docs --dest-dir $READTHEDOCS_OUTPUT/html
