name: ZLUDA
on:
  workflow_dispatch:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: "true"
  CARGO_PROFILE: release-lto
  ROCM_VERSION: "6.3.1"

jobs:
  build_linux:
    name: Build (Linux)
    runs-on: ubuntu-22.04
    steps:
    - uses: jlumbroso/free-disk-space@main
      with:
        # Removing Android stuff should be enough
        android: true
        dotnet: false
        haskell: false
        large-packages: false
        docker-images: false
        swap-storage: false
      with:
        submodules: true
    - uses: actions/checkout@v4
    - name: Install ROCm
      run: sudo bash .github/workflows/rocm_setup_build.sh ${{ env.ROCM_VERSION }}
    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.9
    - name: Build
      # https://github.com/actions/upload-artifact/issues/39
      run: |
        cargo xtask zip --profile ${{ env.CARGO_PROFILE }}
        mkdir target/${{ env.CARGO_PROFILE }}/zluda
        tar -xzf target/${{ env.CARGO_PROFILE }}/zluda.tar.gz -C target/${{ env.CARGO_PROFILE }}/zluda
    - name: Set revision hash
      run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: zluda-linux-${{ env.SHORT_SHA }}
        path: target/${{ env.CARGO_PROFILE }}/zluda
  build_windows:
    name: Build (Windows)
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.9
    - name: Build
      run: |
        cargo xtask zip --profile ${{ env.CARGO_PROFILE }}
        Expand-Archive -Path target/${{ env.CARGO_PROFILE }}/zluda.zip -DestinationPath target/${{ env.CARGO_PROFILE }}/zluda
    - name: Set revision hash
      run: echo "SHORT_SHA=$("${{ github.sha }}".SubString(0, 7))" >> $env:GITHUB_ENV
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: zluda-windows-${{ env.SHORT_SHA }}
        path: target/${{ env.CARGO_PROFILE }}/zluda
